name: Publish Extension

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Zip extension
        run: zip -r extension.zip ./src -x "*.git*" ".github/*"

      - name: Upload to Chrome Web Store
        uses: Klemensas/chrome-extension-upload-action@v2
        with:
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          app-id: ${{ secrets.CHROME_EXTENSION_ID }}
          zip-path: ./extension.zip
          publish: true
